config/routes.rb
Rails.application.routes.draw do

   root 'home#index'

     resources :users

    post '/signin', to:'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/message/:id', to: 'bot#message', as: :message
    get '/about', to: 'bot#index', as: :about
    get '/contact', to: 'home#show', as: :contact

end

app/models/user.rb
# require_relative 'biometric_face_authentication_api'
class User < ActiveRecord::Base
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user= User.new  
  end

  def create
    @user=User.new(user_params)
    @user.save
    if @user.save
       userRegister = BiometricFaceAuthentication.new
	     response = userRegister.register(@user.username)
	     if response  == "MATCHED"
	        redirect_to user_path(@user.id),notice: "New user created."
	     else
             render 'new'
        end
    end

  end 


  def index
  end


  def show
  	@user=User.find(params[:id])
    @bot = Bot.new(name: "minkbot", data_file: "bot_data")
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    @oldUserName = @user.username
    @user = User.update(@user.id, user_params)
    if @user.save
      @newUserName = @user.username
    end
    userUpdate = BiometricFaceAuthentication.new
    response = userUpdate.edit(@oldUserName , @newUserName)
    if response != nil && response["trained"] == true
          session[:user_id]=@user.id
          redirect_to user_path(@user.id),notice: "User Account updated."
       else
        
        redirect_to  user_path , method: :put
      end
  end

  def destroy
    @user = User.find params[:id]
    userDelete = BiometricFaceAuthentication.new
    response = userDelete.request_delete(@user.username)
    @user.destroy
    redirect_to  root_path 
  end

  def delete
  end


  private

  def user_params
  	params.require(:user).permit(:username, :email)
  end
end

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<div id="signup_pic">
		<div class="form_class"><%= form_for @user do |f| %>
		  
		  <%= f.text_field :username, required: true, :placeholder => 'Username' %><br />
		  
		 
		  <%= f.email_field :email , :placeholder => 'email'%><br />
		  
		  <%= f.submit "Update", class: :form_button %>
		  
		  <% end %>
		</div>
	</div>

app/views/users/new.html.erb
<%= render 'shared/header' %>
    <title>Agent Biometric Log-In</title>
    <link href="css/camera.css" rel="stylesheet" type="text/css" />
    <h1>Face Recognition Test</h1>
    <div id='camera'>
      <div id='placeholder'>
	  <input type="file" accept="image/*" capture="camera" />
        <p>Your browser does not support a camera!</p>
      </div>
    </div>
    <br>
    <input id='photo_id' placeholder='Enter Log-In ID' type='text'>
    <button id='add_to_collection'>Add To Collection</button>
    <br>
    <div id='upload_status'></div>
    <div id='upload_result'></div>
    <br>
    <img height='100' id='loading_img' src='images/loading.gif' width='100'>
    <audio id='audio_speech' src='#'></audio>
    <br>
    <br>
    <p>
      <a href="/collection/create">Create Collection</a> | <a href="/collection/delete">Delete Collection</a>
    </p>


		<div class="form_class"><%= form_for @user do |f| %>

   <%= f.text_field :username, required: true, :placeholder => 'Username' %><br>

		  <%= f.email_field :email , :placeholder => 'email'%><br />
		  
		  <%= f.submit "sign up", class: :form_button %>
		  
		</div>
	</div>
<% end %>

app/views/users/show.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
       <h2 id ="logo" >Hello <%= @user.username %> you successfully logged in</h2>
          <nav>
             <ul class="nav navbar-nav navbar-right">
             <li><%= link_to "Edit Account",edit_user_path(params[:id]), method: :get %></li>
             <li><%= link_to "Delete Account",user_path, method: :delete %></li>
             <li><%= link_to "Log-out", logout_path, method: :delete %></li>
             </ul>
          </nav>
     </div>
  </header>   
     <div class="container">
              <div class="row">
                <div class="col-xs-16 col-md-11">
                  <div class="bubble1">
                  
                  
                  </div>
                  <div class="bubble2">
                  
                  </div>
                </div>
      
             
                <div class="col-xs-16 col-md-11">
                  
                </div>
              </div>
      </div>
     <%= form_tag(message_path(@user.id), method: :get, id: "chat", class: "form_class",remote: :true) do %>
        <%= text_area_tag 'userInput','hi',:placeholder => "Enter your message here" %>
        <%= submit_tag "send", data: {disable_with: "Sending..."} %>
     <%end%>
            



<script type="text/javascript">
  var userName = "<%= @user.username %>"              
</script>