config/routes.rb
Rails.application.routes.draw do

   root 'home#index'

     resources :users

    post '/signin', to:'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/message/:id', to: 'bot#message', as: :message
    get '/about', to: 'bot#index', as: :about
    get '/contact', to: 'home#show', as: :contact

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/views/home/index.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Minkbot!</h1>

    <h2>Minkbot, can chat with you ..he can remember your face !!</h2>
</div>

<nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "New Member? Sign up now!", new_user_path%></li>
        <li> <%= link_to "Log in to chat with me !", users_path %></li>
      </ul>
</nav>
<%= link_to image_tag("http://millennialceo.com/wp-content/uploads/2014/11/Social-Network-Bot.jpg", alt: "Minkbot logo"),
            'http://rubyonrails.org/', class: "minkbot-image" %>

app/views/home/show.html.erb
<div class="center jumbotron">
 <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Somya Belur Narayana", 'TBD', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Linkdin",   'https://www.linkedin.com/in/somyabn' %></li>
        <li><%= link_to "Twitter",   'https://@BnSomya' %></li>
        <li><%= link_to "Github", 'https://github.com/somyabn' %></li>
        <li><%= link_to "Home",   root_path %></li>
      </ul>
    </nav>
  </div>
</header>
</div>